### ISSUE TITLE
remove Text Option

### ISSUE THREAD

**Issue by PetrusJVollgraaff** [gniziemazity/advanced_drawing_app#33]
In order to remove Text Option I need to remove all the text. is there to use the Del Button to determine whether to delete the inner text charater or the remove the Text Option as per video 
1st delete the charators
2de delete the Text option once off

https://github.com/user-attachments/assets/065ed960-cf43-42f6-9869-c5db4b033c2f

**Comment by Iyusuf40** [comment]
There is a way to do this:
- by selecting the text shape using `rectangle select`, i mean by drawing the select box over the text it will select the text without entering edit mode.
- by using `ctrl-A` if it is the only shape on the canvas

However, I agree with you this is not the most intuitive way to do this. A plausible solution would be
- to click on it to select, while to double click on it to enter edit mode
- or to click on it to select, then click on the selected text to enter edit mode

There was a time @gniziemazity does not like the double click behavior on a different matter some time ago, I'd wait to see his decision on this.

**Comment by gniziemazity** [comment]
Good point @PetrusJVollgraaff 
And yes, @Iyusuf40, I think double click is a bad idea if eventually we focus on the mobile experience. But clicking first to select and then once more to enter editing mode sounds like a good idea.

**Comment by Iyusuf40** [comment]
I'd try to to impart the second behaviour.

**Comment by gniziemazity** [comment]
@Iyusuf40 looks like you did!
